### ISSUE TITLE
its not working for imported projects

### ISSUE THREAD

**Issue by senshe** [telosys-eclipse-v3/TelosysToolsPlugin#2]
Thank your for the amazing Telosys

Overview of the issue:

The eclipse plugin is not working on an imported (maven or gradle ) project.

Steps to reproduce the issue:

- import a maven project (or gradle)
- configure the plugin Properties > Telosys Tools > then click on  Initialize Telosys Tools
- try to open databases.dbcfg an IoExeption will appear

Additional notes:

Telosys Tools Plugin Version : 3.0.0.014 - Plugin build 014 (#4)  ( 2018-04-09 ) 

IDE Spring Tool Suite 4 Version: 4.0.1.RELEASE (Eclipse )

**Comment by l-gu** [comment]
This bug has been fixed in ver 3.1.2
